//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.03 at 10:25:45 AM CST 
//


package com.ws.msp.legacyPojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Message" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Target" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Source">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="token" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DeliveryReport" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SubmitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DoneDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message"
})
@XmlRootElement(name = "SmsMO")
public class SmsMO {

    @XmlElement(name = "Message", required = true)
    protected List<SmsMO.Message> message;

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SmsMO.Message }
     * 
     * 
     */
    public List<SmsMO.Message> getMessage() {
        if (message == null) {
            message = new ArrayList<SmsMO.Message>();
        }
        return this.message;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Target" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Source">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="token" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DeliveryReport" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SubmitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DoneDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "target",
        "language",
        "text",
        "source",
        "deliveryReport"
    })
    public static class Message {

        @XmlElement(name = "Target", required = true)
        protected String target;
        @XmlElement(name = "Language", required = true)
        protected String language;
        @XmlElement(name = "Text", required = true)
        protected String text;
        @XmlElement(name = "Source", required = true)
        protected SmsMO.Message.Source source;
        @XmlElement(name = "DeliveryReport")
        protected SmsMO.Message.DeliveryReport deliveryReport;

        /**
         * Gets the value of the target property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTarget() {
            return target;
        }

        /**
         * Sets the value of the target property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTarget(String value) {
            this.target = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link SmsMO.Message.Source }
         *     
         */
        public SmsMO.Message.Source getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link SmsMO.Message.Source }
         *     
         */
        public void setSource(SmsMO.Message.Source value) {
            this.source = value;
        }

        /**
         * Gets the value of the deliveryReport property.
         * 
         * @return
         *     possible object is
         *     {@link SmsMO.Message.DeliveryReport }
         *     
         */
        public SmsMO.Message.DeliveryReport getDeliveryReport() {
            return deliveryReport;
        }

        /**
         * Sets the value of the deliveryReport property.
         * 
         * @param value
         *     allowed object is
         *     {@link SmsMO.Message.DeliveryReport }
         *     
         */
        public void setDeliveryReport(SmsMO.Message.DeliveryReport value) {
            this.deliveryReport = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SubmitDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DoneDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Error" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "submitDate",
            "doneDate",
            "state",
            "error"
        })
        public static class DeliveryReport {

            @XmlElement(name = "Id", required = true)
            protected String id;
            @XmlElement(name = "SubmitDate", required = true)
            protected String submitDate;
            @XmlElement(name = "DoneDate", required = true)
            protected String doneDate;
            @XmlElement(name = "State", required = true)
            protected String state;
            @XmlElement(name = "Error", required = true)
            protected String error;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the submitDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubmitDate() {
                return submitDate;
            }

            /**
             * Sets the value of the submitDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubmitDate(String value) {
                this.submitDate = value;
            }

            /**
             * Gets the value of the doneDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDoneDate() {
                return doneDate;
            }

            /**
             * Sets the value of the doneDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDoneDate(String value) {
                this.doneDate = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getState() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setState(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the error property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getError() {
                return error;
            }

            /**
             * Sets the value of the error property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setError(String value) {
                this.error = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="token" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Source {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "token")
            protected String token;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the token property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getToken() {
                return token;
            }

            /**
             * Sets the value of the token property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setToken(String value) {
                this.token = value;
            }

        }

    }

}
